### ISSUE TITLE
BUG Single landuse not implemented

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#18] opened 2018-03-24 00:00 UTC
I got again this error. I am building managements per hillslope so not sure why we are getting this. 

https://wepp1.nkn.uidaho.edu/weppcloud/runs/30401012-510e-4154-85b1-abc50868ca5e/lt/

Error running wepp

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wepppy/weppcloud/app.py", line 1520, in submit_task_run_wepp
    wepp.prep_hillslopes()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/wepp.py", line 217, in prep_hillslopes
    self._prep_managements(translator)
  File "/usr/lib/python3/dist-packages/wepppy/nodb/wepp.py", line 289, in _prep_managements
    raise NotImplementedError('Single landuse not implemented')
NotImplementedError: Single landuse not implemented

**Comment by rogerlew** [comment] 2018-03-24 01:43
duplicate of issue #14

**Closed by rogerlew** 2018-03-24 01:43 UTC
